import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import { Toaster } from "sonner";
import { AuthProvider } from "@/contexts/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trivia Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <AuthProvider>

        <body className="min-h-full flex bg-black flex-col ">

          <Header />
          <div className="flex items-center justify-center flex-1">
            {children}
          </div>
          <Toaster />

        </body>
      </AuthProvider>
    </html>
  );
}
